### ISSUE TITLE
No solved-icon at thread page.

### ISSUE THREAD

**Issue by MvGulik** [LaveIT/MyBB-Plugin-Mark-Thread-as-done-solved#1]
Hi

At the python-forum.io forum there using your MyBBS "Mark Thread as done/solved" plugin. But for some reason the solved-icon has only showed up at the forum-index pages (_img1_). But not, for example, at thread pages themself (_img2_) (_not sure if there are other MyBBS locations it should show_).

([Related post at forum](https://python-forum.io/Thread-simple-solved-plugin?pid=80327#pid80327))

Might you have some initial ideas why that might have happened, or how this might be fixed **?**

(_ps: I'm just a general user at python-forum.io forum hoping this can be fixed_)

Img1) (_link: [Forum-Board](https://python-forum.io/Forum-Board)_)
![image](https://user-images.githubusercontent.com/666868/57716353-1790d980-7679-11e9-9574-8a186b429911.png)

Img2) (_link: [Thread-simple-solved-plugin](https://python-forum.io/Thread-simple-solved-plugin)_)
![image](https://user-images.githubusercontent.com/666868/57716510-77878000-7679-11e9-86cf-1cbfc322d5fc.png)

**Comment by LaveIT** [comment]
Hi,

please change the "showthread" Template in your theme.

Search for 

`<strong>{$thread['displayprefix']}{$thread['subject']}</strong>`

and change to

`{$threadsolved}<strong>{$thread['displayprefix']}{$thread['subject']}</strong>`


Maybe the forum owner intentionally removed this variable because he wanted it to be different.

**Comment by MvGulik** [comment]
Thanks for your help/support,
and thanks for switching to related forum. :-)

That did the trick, thanks :-)
(closing)
